"""Serving-size calculation for the nutrition data layer.

Nutrition is stored on a per-100g basis. Given a per-100g record and an
estimated serving size, scale linearly:

    nutrition_for_serving = nutrition_per_100g * serving_size_g / 100

The final serving-level values come from the nutrition database scaled by the
estimate — never generated by the recognition model.
"""

from ..models.food import FoodNutrition, ServingNutrition


def nutrition_for_serving(
    nutrition: FoodNutrition,
    serving_size_g: float,
) -> ServingNutrition:
    """Scale a per-100g nutrition record to a specific serving size."""
    factor = serving_size_g / 100.0
    return ServingNutrition(
        food_id=nutrition.food_id,
        serving_size_g=serving_size_g,
        carbs_g=round(nutrition.carbs_g_per_100g * factor, 1),
        protein_g=round(nutrition.protein_g_per_100g * factor, 1),
        fat_g=round(nutrition.fat_g_per_100g * factor, 1),
        fiber_g=round(nutrition.fiber_g_per_100g * factor, 1),
        calories=round(nutrition.calories_per_100g * factor, 1),
        nutrition_source=nutrition.nutrition_source,
    )