// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMYcYehLTZTkylnjv7QOkZFve-JLg5uwk',
    appId: '1:511794664128:web:39302ceeebb371fa46d325',
    messagingSenderId: '511794664128',
    projectId: 'glucosaathi',
    authDomain: 'glucosaathi.firebaseapp.com',
    storageBucket: 'glucosaathi.firebasestorage.app',
    measurementId: 'G-Q5QMB9CBLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyNCo1sbKRF3smWW4um8c0JbrkJarutcc',
    appId: '1:511794664128:android:a9a87913c6ff919a46d325',
    messagingSenderId: '511794664128',
    projectId: 'glucosaathi',
    storageBucket: 'glucosaathi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcWvpshUci0ZVKBLJdMwKtX92PukSHe1Y',
    appId: '1:511794664128:ios:476525596de2971c46d325',
    messagingSenderId: '511794664128',
    projectId: 'glucosaathi',
    storageBucket: 'glucosaathi.firebasestorage.app',
    iosBundleId: 'com.example.glucosaathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcWvpshUci0ZVKBLJdMwKtX92PukSHe1Y',
    appId: '1:511794664128:ios:476525596de2971c46d325',
    messagingSenderId: '511794664128',
    projectId: 'glucosaathi',
    storageBucket: 'glucosaathi.firebasestorage.app',
    iosBundleId: 'com.example.glucosaathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMYcYehLTZTkylnjv7QOkZFve-JLg5uwk',
    appId: '1:511794664128:web:6c475e81a9cd122446d325',
    messagingSenderId: '511794664128',
    projectId: 'glucosaathi',
    authDomain: 'glucosaathi.firebaseapp.com',
    storageBucket: 'glucosaathi.firebasestorage.app',
    measurementId: 'G-HC4HRTMSCM',
  );
}
