"""Common food name aliases for Gemini → INDB matching.

Maps common alternative food names (as returned by Gemini Vision) to the
canonical names or primary aliases used in the INDB dataset. Keys are
normalized (lowercase, punctuation-stripped) so they can be looked up after
``normalize_label()`` is applied to the Gemini output.

This bridges the gap between how users/Gemini name foods (e.g. "Chapati",
"Chicken Biryani") and how INDB stores them (e.g. "Roti", "Biryani, chicken").
"""

from typing import Dict

# fmt: off
FOOD_COMMON_ALIASES: Dict[str, str] = {
    # Breads & Rotis
    "chapati":              "roti",
    "chapati roti":         "roti",
    "roti chapati":         "roti",
    "phulka":               "roti",
    "phulka roti":          "roti",
    "tandoori roti":        "tandoori roti",
    "naan":                 "naan",
    "butter naan":          "butter naan",
    "garlic naan":          "garlic naan",
    "kulcha":               "kulcha",
    "missi roti":           "missi roti",

    # Rice dishes
    "chicken biryani":      "chicken curry",
    "mutton biryani":       "mutton biryani/biriyani",
    "veg biryani":          "vegetable biryani/biriyani",
    "vegetable biryani":    "vegetable biryani/biriyani",
    "hyderabadi biryani":   "mutton biryani/biriyani",
    "jeera rice":           "jeera rice",
    "cumin rice":           "jeera rice",
    "ghee rice":            "ghee rice",
    "peas pulao":           "peas pulao",
    "vegetable pulao":      "vegetable pulao",
    "coconut rice":         "coconut rice",
    "lemon rice":           "lemon rice",
    "tamarind rice":        "tamarind rice",
    "curd rice":            "curd rice",
    "yogurt rice":          "curd rice",
    "tomato rice":          "tomato rice",
    "garlic rice":          "garlic rice",
    "paneer rice":          "paneer rice",
    "egg rice":             "egg rice",
    "fish biryani":         "fish biryani",
    "prawn biryani":        "prawn biryani",
    "bisi bele bath":       "bisi bele bath",
    "pongal":               "pongal",
    "ven pongal":           "ven pongal",
    "sweet pongal":         "sweet pongal",

    # Curries & gravies
    "butter chicken":       "butter chicken",
    "chicken butter masala":"butter chicken",
    "chicken tikka masala": "chicken tikka masala",
    "paneer butter masala": "shahi paneer",
    "paneer makhani":       "shahi paneer",
    "chicken curry":        "chicken curry",
    "mutton curry":         "mutton curry",
    "fish curry":           "fish curry",
    "egg curry":            "egg curry",
    "rajma":                "kidney bean curry (rajmah curry)",
    "rajma curry":          "kidney bean curry (rajmah curry)",
    "kidney bean curry":    "kidney bean curry (rajmah curry)",
    "chana masala":         "chana masala",
    "chole":                "chole",
    "chole bhature":        "chole",
    "dal makhani":          "dal makhani",
    "dal fry":              "dal fry",
    "dal tadka":            "dal tadka",
    "sambar":               "sambar",
    "rasam":                "rasam",
    "korma":                "korma",
    "rogan josh":           "rogan josh",
    "vindaloo":             "vindaloo",
    "madras curry":         "madras curry",
    "kadai":                "kadai",
    "kadahi":               "kadai",
    "jalfrezi":             "jalfrezi",
    "balti":                "balti",
    "bhuna":                "bhuna",
    "tikka masala":         "tikka masala",
    "methi chicken":        "methi chicken",
    "chicken korma":        "chicken korma",
    "mutton korma":         "mutton korma",
    "prawn curry":          "prawn curry",

    # Snacks & street food
    "samosa":               "samosa",
    "aloo samosa":          "samosa",
    "vegetable samosa":     "samosa",
    "pakora":               "pakora",
    "pakoda":               "pakora",
    "vegetable pakora":     "pakora",
    "onion pakora":         "pakora",
    "bhajji":               "pakora",
    "bhaji":                "pakora",
    "vada":                 "medu vada",
    "medu vada":            "medu vada",
    "masala vada":          "masala vada",
    "dahi vada":            "dahi vada",
    "dahi vada":            "dahi vada",
    "aloo tikki":           "aloo tikki",
    "tikki":                "aloo tikki",
    "papdi chaat":          "papdi chaat",
    "gol gappa":            "gol gappa",
    "pani puri":            "gol gappa",
    "pani poori":           "gol gappa",
    "bhel puri":            "bhel puri",
    "sev puri":             "sev puri",
    "dahi puri":            "dahi puri",
    "ragda patties":        "ragda patties",
    "pav bhaji":            "pav bhaji",
    "misal pav":            "misal pav",
    "dabeli":               "dabeli",
    "kanda bhaji":          "onion bhaji",
    "onion bhaji":          "onion bhaji",
    "mirchi bhaji":         "mirchi bhaji",
    "bonda":                "bonda",
    "aloo bonda":           "bonda",
    "bread pakora":         "bread pakora",
    "spring roll":          "spring roll",
    "cutlet":               "cutlet",

    # Dosa & idli
    "masala dosa":          "masala dosa",
    "dosa":                 "masala dosa",
    "plain dosa":           "dosa, plain",
    "rava dosa":            "rava dosa",
    "onion dosa":           "onion dosa",
    "cheese dosa":          "cheese dosa",
    "mysore masala dosa":   "mysore masala dosa",
    "idli":                 "idli",
    "idly":                 "idli",
    "rava idli":            "rava idli",
    "set dosa":             "set dosa",
    "uttapam":              "uttapam",
    "uttappam":             "uttapam",
    "appam":                "appam",
    "palappam":             "appam",
    "pesarattu":            "pesarattu",

    # Parathas
    "aloo paratha":         "potato parantha/paratha (aloo ka parantha/paratha)",
    "aloo parantha":        "potato parantha/paratha (aloo ka parantha/paratha)",
    "gobi paratha":         "cauliflower parantha/paratha (gobhi ka parantha/paratha)",
    "gobi parantha":        "cauliflower parantha/paratha (gobhi ka parantha/paratha)",
    "paneer paratha":       "paneer parantha/paratha",
    "paneer parantha":      "paneer parantha/paratha",
    "plain paratha":        "plain parantha/paratha",
    "plain parantha":       "plain parantha/paratha",
    "paratha":              "plain parantha/paratha",
    "parantha":             "plain parantha/paratha",
    "thepla":               "thepla",
    "methi thepla":         "thepla",

    # Snack items
    "poha":                 "poha",
    "kanda poha":           "poha",
    "indori poha":          "poha",
    "upma":                 "upma",
    "uppma":                "upma",
    "khichdi":              "khichdi",
    "khichri":              "khichdi",
    "moong dal khichdi":    "khichdi",
    "pulao":                "vegetable pulao",
    "pilaf":                "vegetable pulao",

    # South Indian
    "rava dosa":            "rava dosa",
    "cone dosa":            "dosa, plain",
    "paper dosa":           "dosa, plain",
    "ghee roast":           "ghee roast",

    # Egg dishes
    "boiled egg":           "boiled egg",
    "fried egg":            "fried egg",
    "omelette":             "omelette",
    "omelet":               "omelette",
    "egg bhurji":           "egg bhurji",
    "egg curry":            "egg curry",
    "egg masala":           "egg masala",

    # Chicken preparations
    "chicken 65":           "chicken 65",
    "chicken fry":          "chicken fry",
    "chicken tandoori":     "tandoori chicken",
    "tandoori chicken":     "tandoori chicken",
    "chicken kebab":        "chicken kebab",
    "chicken seekh kebab":  "chicken seekh kebab",
    "chicken tikka":        "chicken tikka",
    "chicken masala":       "chicken masala",
    "chicken korma":        "chicken korma",
    "chicken vindaloo":     "vindaloo",
    "chicken jalfrezi":     "jalfrezi",
    "chicken bhuna":        "bhuna",
    "chicken changezi":     "chicken changezi",
    "butter chicken":       "butter chicken",
    "chicken soup":         "chicken soup",
    "chicken soup":         "chicken soup",

    # Mutton/lamb
    "mutton masala":        "mutton masala",
    "mutton rogan josh":    "rogan josh",
    "mutton vindaloo":      "mutton vindaloo",
    "mutton kebab":         "mutton kebab",
    "mutton seekh kebab":   "mutton seekh kebab",
    "lamb curry":           "mutton curry",

    # Fish & seafood
    "fish fry":             "fish fry",
    "fish masala":          "fish masala",
    "fish tikka":           "fish tikka",
    "fish vindaloo":        "fish vindaloo",
    "prawn masala":         "prawn masala",
    "prawn fry":            "prawn fry",
    "shrimp curry":         "prawn curry",
    "shrimp masala":        "prawn masala",

    # Vegetables
    "aloo gobi":            "aloo gobi",
    "aloo jeera":           "aloo jeera",
    "aloo matar":           "aloo matar",
    "aloo tamatar":         "aloo tamatar",
    "palak paneer":         "palak paneer",
    "matar paneer":         "matar paneer",
    "paneer tikka":         "paneer tikka",
    "paneer bhurji":        "paneer bhurji",
    "bhindi masala":        "bhindi masala",
    "okra curry":           "bhindi masala",
    "baingan bharta":       "baingan bharta",
    "brinjal bharta":       "baingan bharta",
    "mix vegetable":        "mixed vegetable curry",
    "mixed vegetables":     "mixed vegetable curry",
    "avial":                "avial",
    "kootu":                "kootu",
    "poriyal":              "poriyal",
    "thoran":               "thoran",
    "dal fry":              "dal fry",
    "dal tadka":            "dal tadka",
    "sambar":               "sambar",
    "rasam":                "rasam",
    "kootu":                "kootu",
    " keerai":              "keerai",
    "keerai kootu":         "keerai kootu",
    "keerai poriyal":       "keerai poriyal",

    # Snacks & sides
    "chips":                "chips",
    "banana chips":         "banana chips",
    "papad":                "papad",
    "papadum":              "papad",
    "pickle":               "pickle",
    "mango pickle":         "mango pickle",
    "lime pickle":          "lime pickle",
    "chutney":              "chutney",
    "coconut chutney":      "coconut chutney",
    "mint chutney":         "mint chutney",
    "tamarind chutney":     "tamarind chutney",
    "raita":                "raita",
    "boondi raita":         "boondi raita",
    "cucumber raita":       "cucumber raita",

    # Sweets & desserts
    "gulab jamun":          "gulab jamun",
    "jalebi":               "jalebi",
    "rasgulla":             "rasgulla",
    "rasmalai":             "rasmalai",
    "gajar ka halwa":       "gajar ka halwa",
    "carrot halwa":         "gajar ka halwa",
    "moong dal halwa":      "moong dal halwa",
    "kheer":                "kheer",
    "payasam":              "payasam",
    "sevai kheer":          "sevai kheer",
    "sheer khurma":         "sheer khurma",
    "kulfi":                "kulfi",
    "kulfis":               "kulfi",
    "ras malai":            "rasmalai",
    "gulab jamun":          "gulab jamun",
    "imarti":               "imarti",
    "malpua":               "malpua",
    "shrikhand":            "shrikhand",
    "mysore pak":           "mysore pak",
    "ladoo":                "ladoo",
    "besan ladoo":          "ladoo",
    "motichoor ladoo":      "ladoo",
    "coconut barfi":        "coconut barfi",
    "kaju katli":           "kaju katli",
    "burfi":                "barfi",
    "barfi":                "barfi",
    "kalakand":             "kalakand",
    "halwa":                "halwa",
    "suji halwa":           "halwa",
    "atta halwa":           "halwa",

    # Beverages
    "chai":                 "tea",
    "masala chai":          "masala chai",
    "tea":                  "tea",
    "green tea":            "green tea",
    "black tea":            "tea",
    "filter coffee":        "filter coffee",
    "coffee":               "filter coffee",
    "cold coffee":          "cold coffee",
    "lassi":                "lassi",
    "sweet lassi":          "lassi",
    "mango lassi":          "mango lassi",
    "buttermilk":           "buttermilk",
    "chaas":                "buttermilk",
    "nimbu pani":           "nimbu pani",
    "lemon water":          "nimbu pani",
    "jaljeera":             "jaljeera",
    "aam panna":            "aam panna",
    "thandai":              "thandai",
    "badam milk":           "badam milk",
    "almond milk":          "badam milk",
    "sattu drink":          "sattu drink",
    "sharbat":              "sharbat",
    "rooh afza":            "rooh afza",

    # Bread items
    "bread":                "bread",
    "white bread":          "bread",
    "brown bread":          "brown bread",
    "whole wheat bread":    "brown bread",
    "pav":                  "pav",
    "ladi pav":             "pav",
    "bun":                  "bun",
    "kulcha":               "kulcha",
    "amritsari kulcha":     "amritsari kulcha",

    # Packaged / processed
    "maggi":                "instant noodles",
    "instant noodles":      "instant noodles",
    "noodles":              "noodles",
    "pasta":                "pasta",
    "bread toast":          "bread",
    "toast":                "bread",
    "corn flakes":          "corn flakes",
    "muesli":               "muesli",
    "oats":                 "oats",
    "oatmeal":              "oats",
    "pizza":                "pizza",
    "burger":               "burger",
    "sandwich":             "sandwich",
    "grilled sandwich":     "sandwich",
    "cheese sandwich":      "sandwich",

    # Condiments & extras
    "ghee":                 "ghee",
    "butter":               "butter",
    "cream":                "cream",
    "malai":                "cream",
    "curd":                 "curd",
    "yogurt":               "curd",
    "dahi":                 "curd",
    "sugar":                "sugar",
    "honey":                "honey",
    "jaggery":              "jaggery",
    "gur":                  "jaggery",
    "salt":                 "salt",
    "oil":                  "oil",
    "mustard oil":          "mustard oil",
    "coconut oil":          "coconut oil",
    "olive oil":            "olive oil",
    "lemon":                "lemon",
    "lime":                 "lemon",
    "tomato":               "tomato",
    "onion":                "onion",
    "garlic":               "garlic",
    "ginger":               "ginger",
    "green chilli":         "green chilli",
    "coriander":            "coriander",
    "mint":                 "mint",
    "curry leaves":         "curry leaves",
    "coconut":              "coconut",

    # Meals / combos (INDB may not have exact matches; map to closest)
    "thali":                "thali",
    "meals":                "meals",
    "south indian meals":   "meals",
    "north indian meals":   "meals",
    "vegetable thali":      "thali",
    "non veg thali":        "thali",
}
# fmt: on


def resolve_common_alias(name: str) -> str:
    """Map a common food name to its INDB alias/primary name.

    Returns the original ``name`` unchanged if no common alias exists.
    The lookup is case-insensitive; ``name`` is lowercased and
    punctuation-stripped before matching.
    """
    from ..database.sqlite import normalize_label

    normalized = normalize_alias(name)
    return FOOD_COMMON_ALIASES.get(normalized, name)


def normalize_alias(name: str) -> str:
    """Lowercase, strip punctuation (except '/'), collapse whitespace, trim."""
    import re

    normalized = name.strip().lower()
    # Remove punctuation except slashes (used in INDB names like "parantha/paratha")
    normalized = re.sub(r"[^\w\s/]", "", normalized)
    return " ".join(normalized.split())
